### ISSUE TITLE
How to load data correctly?

### ISSUE THREAD

**Issue by gurbee** [apple/ml-4m#25]
Thank you all for your awesome work and open souce code, although there are really detailed instuctions, I am still confused at the data path and data preperation process, when applying to the object detection task.

### My data path and cfg settings
Task: object detection
Input: Image, Output: bbox

To the best of my knowledge, the pretokenization is optional, so I choose to prepare my data as README_DATA.md introduced for finetuing a small dataset:

root/rgb/000.jpg
root/rgb/001.jpg
root/rgb/002.jpg

root/det/000.txt
root/det/001.txt
root/det/002.txt

Which the txt for detection labeling includes classid and bbox information as follows:
```
<class> <x_center> <y_center> <width> <height>
``` 

And I also made the necessary modifications in data cfg, including:
data_path: 'root'
modality_name_map:
     rgb: rgb@224
     det: det

### Error message
```shell
[rank0]: RuntimeError: Found 0 logs in subfolders of: root/det
[rank0]: Supported extensions are: .jpg,.jpeg,.png,.ppm,.bmp,.pgm,.tif,.tiff,.webp,.jpx,.npy,.npz,.json,.txt,.json.gz
``` 
However, error message shows that it is not able to read the content, I printed the length of "instance" list return by the fourm/data/multimodasl_dataset_folder/make_dataset function, the length of return object is 0, I think that is the problem, but I don't understand why?

### COCO det annotation 
I read in the paper appendix that Bounding boxes modality is fine-tuned on COCO, so I also tried the detection label in .json format, but I am also confused of how to load det path in cfg?

My coco annotation is in the format as follows:
```javascript
{
    "images": [
        {
            "file_name": "000.jpg",
            "height": 1035,
            "width": 1380,
            "id": 0
        }
    ],
 "categories": [
        {
            "supercategory": "Defect",
            "id": 0,
            "name": "Defect_class1"
        }
    ],
    "annotations": [
        {
            "id": 1,
            "image_id": 0,
            "bbox": [
                785.0,
                670.0,
                100.0,
                110.0
            ],
            "area": 11000,
            "iscrowd": 0,
            "category_id": 1,
            "segmentation": []
        }
    ]
}
``` 

I am really looking forward to finetune your work, thank you for all for your support!

**Comment by garjania** [comment]
Hi @gurbee,

On the data loading part, following what is mentioned in README_DATA, your dataset structure should be something like:
```
root/rgb/folder_x/000.jpg
root/rgb/folder_x/001.jpg
root/rgb/folder_x/002.jpg

root/det/folder_x/000.json
root/det/folder_x/001.json
root/det/folder_x/002. json
```
As you can see for detection we are using the JSON format. Each JSON file should have the following structure:

```
{
   'num_instances': n, #Number of instances in the image
   'image_height': h,
   'image_width': w,
   'instances': [
       {
          'boxes': [x1,y1,h,w], #Bbox starting point, height, and width on a scale of [0,1]
          'score': , #Bbox score assigned during pseudo-labeling
          'class_id': id,
          'class_name': name,
        },
        ...
   ]
}
```

**Comment by gurbee** [comment]
Thank you @garjania, really appreciated!!

**Comment by sumedh7** [comment]
Hi @garjania, thanks again for the great work!
When you load jsons here: https://github.com/apple/ml-4m/blob/ee81e40983616e9737f444068572f0bac9961abe/fourm/data/modality_transforms.py#L659

You seem to expect `[xmin, ymin, xmax, ymax, class_name, score]` but your comment above says otherwise. Just wondering if there is some discrepancy.
Also you say
`'boxes': [x1,y1,h,w], #Bbox starting point, height, and width on a scale of [0,1]
`
But its usually `[x1,y1,w,h]` in other detection libraries. 
Can you please confirm which is the correct order?
Thanks!
