### ISSUE TITLE
 AttributeError: module 'albumentations' has no attribute 'bbox_crop'

### ISSUE THREAD

**Issue by gurbee** [apple/ml-4m#28]
Thank you all for your hard work, I have encountered function not exist issue as follows, really looking forward to implement it!
Function not exist in import package, bbox_crop function is not found.

file:  fourm/data/modality_transfroms.py/DetectionTransform/bboxes_crop_resize/modality_transforms.py
code: line 689
package version: 
```shell
# Name                    Version                   Build  Channel
albumentations            1.4.12                   pypi_0    pypi
```
![image](https://github.com/user-attachments/assets/0b5dca48-b0a5-4fe7-adf3-bafc009dc68d)

```code
import albumentations as A

bboxes = [tuple(A.bbox_crop(bbox[:4], x_min=xmin, y_min=ymin, x_max=xmax, y_max=ymax, rows=orig_height, cols=orig_width)) + tuple(bbox[4:]) for bbox in bboxes]
```

**Comment by sumedh7** [comment]
I found the following to work:
`pip install albumentations==1.4.0`

**Comment by gurbee** [comment]
I solved this problem by reinstalling albumentations to old version too.

**Comment by gurbee** [comment]
I solved this problem by reinstalling albumentations to old version too.
